Commit fourmolu changes on CI (#332)
fixes #328

---------

Co-authored-by: github-actions <github-actions@github.com>

diff --git a/booster/.github/workflows/test.yml b/booster/.github/workflows/test.yml
--- a/booster/.github/workflows/test.yml
+++ b/booster/.github/workflows/test.yml
@@ -119,8 +119,8 @@ jobs:
       - name: 'Checkout Code'
         uses: actions/checkout@v3
         with:
-          # Check out pull request HEAD instead of merge commit.
-          ref: ${{ github.event.pull_request.head.sha }}
+          ref: ${{ github.event.pull_request.head.ref }}
+          token: ${{ secrets.JENKINS_GITHUB_PAT }}
 
       - name: 'Set up Docker'
         uses: ./.github/actions/with-docker
@@ -134,7 +134,27 @@ jobs:
           ghc: ${{ env.ghc_version }}
 
       - name: 'Check formatting'
-        run: docker exec -t hs-booster-ci-formatting-style-buster-${{ github.run_id }} /bin/bash -c './scripts/fourmolu.sh && git diff --exit-code'
+        run: docker exec -t hs-booster-ci-formatting-style-buster-${{ github.run_id }} /bin/bash -c './scripts/fourmolu.sh'
+
+      - name: Update branch
+        env:
+          GITHUB_EVENT_NAME: ${{ github.event_name }}
+        run: |
+          if git status -s -b | grep -q '^##.*(no branch)$'; then
+            echo 2>&1 "Error: Git is in detached HEAD state"
+            exit 1
+          fi
+
+          if [ -n "$(git status --porcelain '*.hs')" ]; then
+            git config --global user.name github-actions
+            git config --global user.email github-actions@github.com
+            git add '*.hs'
+            git commit -m "Format with fourmolu"
+            git show --stat
+            git push
+            echo "Reformatted code pushed, aborting this workflow" | tee -a $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
       - name: 'Run hlint'
         run: docker exec -t hs-booster-ci-formatting-style-buster-${{ github.run_id }} /bin/bash -c './scripts/hlint.sh'
@@ -143,6 +163,7 @@ jobs:
         if: always()
         run: |
           docker stop --time=0 hs-booster-ci-formatting-style-buster-${{ github.run_id }}
+
 
   nix-build:
     name: 'Nix / All Tests'
