added haddoc runs to PR and master (for caching)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -175,6 +175,61 @@ jobs:
       - name: Run unit tests
         run: stack test --pedantic
 
+      - name: Check documentation
+        run: |
+          stack haddock \
+            --fast \
+            >haddock.log 2>&1 \
+            || ( cat haddock.log; exit 1; )
+          #remove header warning for Paths_kore
+          sed -e "/.*in 'Paths_kore'$/{n;n;/^ *Module header$/d}" haddock.log | tee haddock.log.noPaths
+          if grep -B 2 'Module header' haddock.log.noPaths; then \
+            echo >&2 "Please fix the missing documentation!"; \
+            exit 1; \
+          fi
+
+  stack-haddock:
+    name: 'Stack / Haddock check'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install prerequisites
+        run: |
+          sudo apt install --yes z3
+
+      - uses: actions/checkout@v2.3.4
+        with:
+          # Check out pull request HEAD instead of merge commit.
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: recursive
+
+      - name: Cache Stack root
+        uses: actions/cache@v2
+        with:
+          path: ~/.stack
+          key: stack-haddock-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
+          restore-keys: |
+            stack-haddock-${{ runner.os }}-
+            stack-haddock-
+
+      - uses: haskell/actions/setup@v1
+        id: setup-haskell-stack
+        with:
+          enable-stack: true
+          stack-no-global: true
+          stack-setup-ghc: true
+
+      - name: Check documentation
+        run: |
+          stack haddock \
+            --fast \
+            >haddock.log 2>&1 \
+            || ( cat haddock.log; exit 1; )
+          #remove header warning for Paths_kore
+          sed -e "/.*in 'Paths_kore'$/{n;n;/^ *Module header$/d}" haddock.log | tee haddock.log.noPaths
+          if grep -B 2 'Module header' haddock.log.noPaths; then \
+            echo >&2 "Please fix the missing documentation!"; \
+            exit 1; \
+          fi
   hlint:
     name: 'HLint'
     runs-on: ubuntu-latest
